- hosts: all
  become: yes
  vars_files:
    - users.yml
  vars:
    path_to_doors_code: "/home/pi/projekt_drzwi_otwarte/"
    banner:
      logo: "{{ lookup('file', 'anime_girl.txt') }}"
      # message: "Some message"
  roles:
    - users
    - door_opener