- name: Reboot rasp
  reboot:

- name: Reload door reader
  systemd:
    state: restarted
    name: door_reader.service 

- name: Reload door worker
  systemd:
    state: restarted
    name: door_worker.service 
