---
# tasks file for door_opener
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Ensure i2c-tools package is present or install it
  apt:
    name: i2c-tools
    state: present

- name: Ensure sqlite3 is installed
  apt:
    name: sqlite3
    state: present

- name: Ensure libsqlite3-dev is installed
  apt:
    name: libsqlite3-dev
    state: present

- name: Ensure py532lib python module is present
  pip:
    name: py532lib
    executable: pip3

- name: Set up static IP
  copy:
    src: etc/dhcpcd.conf
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 664
  notify:
   - Reboot rasp

- name: Set up anime girl
  copy:
    src: etc/bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: netdev
    mode: 644
