---
# tasks file for door_opener
- name: Ensure i2c-tools package is present or install it
  apt:
    name: i2c-tools
    state: present
    update_cache: true

- name: Ensure py532lib python module is present
  pip:
    name: py532lib
    executable: pip3

