---
# tasks file for door_opener
- name: Update and upgrade apt packages
  apt:
    upgrade: 'yes'
    update_cache: 'yes'

- name: Ensure required packages are present or install them
  apt:
    name: i2c-tools,sqlite3,libsqlite3-dev,screen
    state: present

- name: Ensure py532lib python module is present
  pip:
    name: py532lib
    executable: pip3

- name: Set up static IP
  copy:
    src: etc/dhcpcd.conf
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664
  notify:
   - Reboot rasp

- name: Ensure correct .bashrc for user pi
  copy:
    src: home/pi/.bashrc
    dest: /home/pi/.bashrc
    owner: pi
    group: pi
    mode: 0644

- name: Ensure .bash_aliases for user pi
  copy:
    src: home/pi/.bash_aliases
    dest: /home/pi/.bash_aliases
    owner: pi
    group: pi
    mode: 0644

# TODO: If the code has changed we need to reload door daemon 
- name: Copy the code into rasp
  synchronize:
    src: ../Kod
    dest: {{ path_to_doors_code }}
    archive: no
    recursive: yes
    checksum: yes
    rsync_opts:
      - "--exclude=*.md"
  tags: [code]

- name: Copy scripts into rasp
  synchronize:
    src: ../Skrypty
    dest: {{ path_to_doors_code }}
    archive: no
    recursive: yes
    checksum: yes
  tags: [code]

- name: Fix ownership
  file:
    path: {{ path_to_doors_code }}
    recurse: yes
    owner: pi
    group: pi
  tags: [code]

- name: Creates a cron for logs remover
  cron:
    name: Database logs remover
    special_time: daily
    user: pi
    job: "${DOOR_HOME}/Skrypty/remove-logs.sh"

- name: Create service configuration for door daemon
  template: 
    src: door.service.j2 
    dest: /lib/systemd/system/door.service 
    mode: 644
  notify:
    - Reload systemctl

- name: Start door daemon
  service: 
    name: door.service 
    state: started 
    enabled: yes
