---
# tasks file for door_opener
- name: Ensure i2c-tools package is present or install it
  apt:
    name: i2c-tools
    state: present
    update_cache: true

- name: Set up static IP
  copy:
    src: etc/dhcpcd.conf
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 664
  notify:
   - Reboot rasp