---
# tasks file for users
- name: Create remote_access group
  group:
    name: remote_access
    state: present
  tags: [users]

- name: Add users
  user:
    name: "{{ item.login }}"
    groups: "users{% if 'groups' in item %},{{ item.groups|join(',') }}{% endif %}"
    shell: "/bin/bash"
    append: yes
    comment: "{{ item.fullname }}"
  with_items: "{{ users }}"
  tags: [users]

- name: Setup authorized keys for users
  authorized_key:
    user: "{{ item.login }}"
    key: "{{ item.pubkey }}"
  with_items: "{{ users }}"
  tags: [users]

- name: Install sshd_banner
  template:
    src: etc/ssh/sshd_banner
    dest: /etc/ssh/sshd_banner
    mode: 0644
    owner: root
    group: root
  when: banner is defined
  tags: [users]

- name: Install sshd_config
  template:
    src: "etc/ssh/sshd_config"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
  - restart sshd
  tags: [users]

- name: Allow sudo_group group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'
  tags: [users]
